#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Sensor, S2,     HTIRS2,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HTIRS2-driver.h"

void initializeRobot() {
    motor[motorA] = 0;  //Set all motors to zero.
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;

	tHTIRS2DSPMode _mode = DSP_1200; set DSP mode to 1200 Hz.
	if (HTIRS2setDSPMode(HTIRS2, _mode) == 0) { // attempt to set to DSP mode.
		eraseDisplay();  // unsuccessful at setting the mode; display error message.
		nxtDisplayCenteredTextLine(0, "ERROR!");
		nxtDisplayCenteredTextLine(2, "Init failed!");
		nxtDisplayCenteredTextLine(3, "Connect sensor");
		nxtDisplayCenteredTextLine(4, "to Port 1.");
		
		wait10Msec(300); // wait so user can read message, then leave main task.
		return;
	}
	eraseDisplay();
}

void stopRobot() {
	motor[motorA] = 0;  //Set all motors to zero.
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
}

int getIRDirection() {
	int IRDirection = 0;
	IRDirection = HTIRS2readACDir(HTIRS2); // read the current modulated signal direction
	if (IRDirection < 0) {
		writeDebugStreamLine("Read dir ERROR!"); // error! - write to debug stream and then break.
		stopRobot();
	}
	else {
	IRDirection -= 5; //Make it so that zero is straight ahead
	return IRDirection;
	}
}

/*int getIRSig() { //This function probably isn't needed
	int IRSig = 0; // the max signal strength from the seeker.
	int S1, S2, S3, S4, S5 = 0; // the five different sections that the sensor returns signal strength for
	if (!HTIRS2readAllACStrength(HTIRS2, S1, S2, S3, S4, S5 )) { // Get the AC signal strength adjustedDirectionues.
		writeDebugStreamLine("Read sig ERROR!");  // error! - write to debug stream and then break.
		stopRobot();
	}  
	else { // find the max signal strength of all detectors.
		IRSig = (S1 > S2) ? S1 : S2;
		IRSig = (IRSig > S3) ? IRSig : S3;
		IRSig = (IRSig > S4) ? IRSig : S4;
		IRSig = (IRSig > S5) ? IRSig : S5;
		return IRSig
	}	
}*/

task main() {
	initializeRobot();
	waitForStart();
	
	while(true) {
		motor[motorD] = 50 + 30 * getIRDirection(); // calculate left and right motor speeds.
		motor[motorE] = 50 - 30 * getIRDirection();
		
		wait10Msec(2);
	}
}
