#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Sensor, S2,     HTIRS2,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HTIRS2-driver.h"

bool error = false;

void initializeRobot() {
    motor[motorA] = 0;  //Set all motors to zero.
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;

	//---------- IR Sensor Initialization ----------//
	tHTIRS2DSPMode _mode = DSP_1200; set DSP mode to 1200 Hz.
	if (HTIRS2setDSPMode(HTIRS2, _mode) == 0) { // attempt to set to DSP mode.
		eraseDisplay();  // unsuccessful at setting the mode; display error message.
		nxtDisplayCenteredTextLine(0, "ERROR!");
		nxtDisplayCenteredTextLine(2, "Init failed!");
		nxtDisplayCenteredTextLine(3, "Connect sensor");
		nxtDisplayCenteredTextLine(4, "to Port 2.");
		error = true;
	}
}

void stopRobot() {
	motor[motorA] = 0;  //Set all motors to zero.
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
}

int getIRDirection() {
	int IRDirection = 0;
	IRDirection = HTIRS2readACDir(HTIRS2); // read the current modulated signal direction
	return IRDirection;
}

void followIR() {
	if (getIRDirection() < 0) {
		writeDebugStreamLine("Read dir ERROR!"); // error! - write to debug stream and then break.
		stopRobot();
	}
	else {
		IRDirection -= 5; //Make it so that zero is straight ahead
		
		nxtDisplayCenteredBigTextLine(1, "Dir=%d", IRDirection());   //Display stuff on the NXT Brick.
			
		motor[motorD] = 50 + 30 * getIRDirection(); // calculate left and right motor speeds.
		motor[motorE] = 50 - 30 * getIRDirection();
		
		wait1Msec(1000);
	}
}

task main() {
	initializeRobot();
	waitForStart();
	
	if (error == true) {  //If the IR Sensor failed to initialize, stop the robot.
		stopRobot();
	}
	else {
		while(true) {
			followIR();
		}
	}
}
