#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void initializeRobot() {
	motor[motorA] = 0;
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
}
void moveRobot() {
	motor[motorD] = 50;
	motor[motorE] = 50;
	wait1Msec(2150);
	motor[motorD] = 0;
	motor[motorE] = 0;
}
void shortMoveRobot() {
	motor[motorD] = 30;
	motor[motorE] = 30;
	wait1Msec(300);
	motor[motorD] = 0;
	motor[motorE] = 0;
}

void rightTurnRobot() {
	motor[motorD] = -30;
	motor[motorE] = 30;
	wait1Msec(350);
	motor[motorD] = 0;
	motor[motorE] = 0;
}
void leftTurnRobot() {
	motor[motorD] = 30;
	motor[motorE] = -30;
	wait1Msec(450);
	motor[motorD] = 0;
	motor[motorE] = 0;
}
void liftArm() {
	motor[motorF] = 70;
	motor[motorA] = -15;
	wait1Msec(800);
	motor[motorF] = 0;
	wait1Msec(1000);
	motor[motorG] = 70;
	wait1Msec(4800);
	motor[motorG] = 0;
}
void lowerArm() {
	motor[motorF] = -15;
	wait1Msec(400);
	motor[motorF] = 0;
	motor[motorG] = -70;
	wait1Msec(4500);
	motor[motorG] = 0;
}
void moveDownWrist() {
	motor[motorA] = 20;
	wait1Msec(800);
	motor[motorA] = 0;
}
void moveUpWrist() {
	motor[motorA] = 20;
	wait1Msec(400);
	motor[motorA] = 0;
}
task main()
{
	initializeRobot();
	//waitForStart();
	moveDownWrist();
	moveRobot();
	liftArm();
	wait1Msec(500);
	rightTurnRobot();
	wait1Msec(750);
	shortMoveRobot();
	wait1Msec(500);
	moveUpWrist();
	lowerArm();

}
